---
bigip_provider:
  server: "{{ bigip_host }}"
  server_port: "{{ bigip_port | default(443, true) }}"
  user: "{{ bigip_user }}"
  password: "{{ bigip_password }}"
  validate_certs: false
as3_state: "{{ application_state|default('present') }}"
as3_template: "{{application_template }}"
as3_app_name: "{{ application_name }}"
as3_tenant: "{{ 'tenant-' + application_name }}"
as3_pool_members: "{{ application_pool_members }}"
as3_share_nodes: true
as3_member_template: "{{ './templates/members-' + application_member_type + '.j2'|default('./templates/members-address.j2') }}"
as3_pool_lb_mode: "{{ application_lb_mode }}"
as3_pool_monitor: "{{ application_pool_monitor }}"
as3_schema_version: 3.17.0





