---
collections:
- name: f5solutionsengineering.ss_cat
  version: '*'
  source: https://github.com/F5SolutionsEngineering/Self-Service-Catalog-Collection/blob/master/f5solutionsengineering/ss_cat/f5solutionsengineering-ss_cat-0.1.tar.gz